# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuitodo" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "e70b7ae356cd5c93f9265e1e5a2d6a89b6cf3046d1ed0e5fbc7fb015d1a94d9c"
      url "https://github.com/vmarinho22/tuitodo/releases/download/v#{version}/tuitodo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "319d9f11f24ceb563557fcd76de8848e3727dfb4ec3c5566a441ac1e79cd4506"
      url "https://github.com/vmarinho22/tuitodo/releases/download/v#{version}/tuitodo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "31c92deae98623cd21e332ceb6b180f6b763935beca6d2bf246ae2a6fa5b52c6"
      url "https://github.com/vmarinho22/tuitodo/releases/download/v#{version}/tuitodo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "136218dd75343e0e9ef6403c895a0655720c7465c24d55a9d6028fce49faaaa9"
      url "https://github.com/vmarinho22/tuitodo/releases/download/v#{version}/tuitodo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tuitodo"
  desc "Local-first terminal todo app"
  homepage "https://github.com/vmarinho22/tuitodo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuitodo"

  # No zap stanza required
end
