# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuitodo" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "0acbf9c129e185003d14cff7b98d5a446676fdd7f2ba3c26369037e4881205b9"
      url "https://github.com/vmarinho22/tuitodo/releases/download/v#{version}/tuitodo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8632678e027bb5aed1e789d8498388ee84c9dd4a4e13e3f4e08af60239f75f1e"
      url "https://github.com/vmarinho22/tuitodo/releases/download/v#{version}/tuitodo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "70ecad7082a1db12abc783b05926aa2bbfb40f72e5c384fab7eff58590a013f7"
      url "https://github.com/vmarinho22/tuitodo/releases/download/v#{version}/tuitodo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "77a11d8e0ae1c08bb3cdeefbaa61c66e9dad75da1f4a39413c334324867b6bb2"
      url "https://github.com/vmarinho22/tuitodo/releases/download/v#{version}/tuitodo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tuitodo"
  desc "Local-first terminal todo app"
  homepage "https://github.com/vmarinho22/tuitodo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuitodo"

  # No zap stanza required
end
