# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuitodo" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "fd5ed0c7a8453d1c424aaf0e2c2d0faf5ae423ad6507c1fde766be644d115dd8"
      url "https://github.com/vmarinho22/tuitodo/releases/download/v#{version}/tuitodo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "346fca37d5bab5328c7cfc35935b53997894acd4803c02e670964aadd4bbff1e"
      url "https://github.com/vmarinho22/tuitodo/releases/download/v#{version}/tuitodo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3234969e7b9a22107d372831b03e2c1488bdcea66cccd02276ae756eca14b562"
      url "https://github.com/vmarinho22/tuitodo/releases/download/v#{version}/tuitodo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b64ad7ef8ce4b69fce98601184646f016daa251341411c8f381a39cf61e3796a"
      url "https://github.com/vmarinho22/tuitodo/releases/download/v#{version}/tuitodo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tuitodo"
  desc "Local-first terminal todo app"
  homepage "https://github.com/vmarinho22/tuitodo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuitodo"

  # No zap stanza required
end
